// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	Name  string         `json:"name"`
	Value pgtype.Numeric `json:"value"`
}
